#!/bin/bash
#
# Generate the Markdown command reference in docs/user/reference/ from the man
# pages in this directory (which are generated from sgml/, see README.md).
#
# Usage: man/make-markdown.sh [<output dir>]    (default: docs/user/reference)
#
# Needs pandoc. The CI checks that the committed Markdown is what this script
# writes, with the pandoc of Ubuntu 24.04: run it there (or in the Ubuntu Dev
# Container) after changing a man page, and commit the result.

set -euo pipefail
# The order of the pages, and the output of pandoc, independent of the locale
export LC_ALL=C

MAN_DIR=$(cd "$(dirname "$0")" && pwd)
OUT=${1:-$MAN_DIR/../docs/user/reference}

mkdir -p "$OUT"
# Only what this script wrote before: a page whose man page is gone goes too
for md in "$OUT"/*.md; do
	if [ -f "$md" ] && head -n1 "$md" | grep -q '^<!-- Generated .*by man/make-markdown.sh'; then
		rm -f "$md"
	fi
done

entries=()
for page in "$MAN_DIR"/*.[18]; do
	file=$(basename "$page")
	name=${file%.*}
	section=${file##*.}
	# The NAME line of the page: "altfs \- File system based on ..."
	desc=$(awk '/^\.SH NAME/ { getline; sub(/^[^ ]* \\- /, ""); print; exit }' "$page")
	entries+=("- [$name($section)]($name.md): $desc")
	{
		echo "<!-- Generated from man/$file by man/make-markdown.sh: edit man/sgml/$name.sgml instead -->"
		echo
		echo "# $name($section)"
		echo
		# The sections become level 2 under the title. Bold and italic that touch
		# ("**-g ***arg*", "*arg***]**", an empty "** **"), from an option and its argument, are not
		# rendered by GitHub: separate them.
		pandoc -f man -t gfm --wrap=preserve --shift-heading-level-by=1 "$page" |
			sed -E -e 's/\*\*([^*]*[^* ]) ?\*\*\*([^*]+)\*/**\1** *\2*/g' \
				-e 's/\*([^* ][^*]*)\*\*\*([^*]+)\*\*/*\1* **\2**/g' \
				-e 's/ \*\* \*\*\*([^*]+)\*/ *\1*/g'
	} > "$OUT/$name.md"
done

{
	echo "<!-- Generated by man/make-markdown.sh -->"
	echo
	echo "# Command reference"
	echo
	echo "The man pages of the commands, as installed with them."
	echo "\`altfsctl\` is installed on Linux only."
	echo
	printf '%s\n' "${entries[@]}"
} > "$OUT/README.md"
