#!/bin/sh

set -e

KERNEL_NAME=`uname -s`

# GENRB/PKGDATA normally come from the parent Makefile with the paths that
# configure detected. The fallbacks below are only for direct invocation.
# On Darwin the ICU tools must come from Homebrew (via PATH); the obsolete
# /Library/Frameworks/ICU.framework (ICU 4.8) generates archives the macOS
# linker cannot read and must not be picked up.
if [ -z "${GENRB}" ]; then
	if [ -x /usr/bin/genrb ] && [ "$KERNEL_NAME" != "Darwin" ]; then
		GENRB=/usr/bin/genrb
	else
		GENRB=genrb
	fi
fi
if [ -z "${PKGDATA}" ]; then
	if [ "$KERNEL_NAME" = "FreeBSD" ]; then
		PKGDATA=/usr/local/bin/pkgdata
	elif [ -x /usr/bin/pkgdata ] && [ "$KERNEL_NAME" != "Darwin" ]; then
		PKGDATA=/usr/bin/pkgdata
	else
		PKGDATA=pkgdata
	fi
fi

# Default tools when not provided by the parent Makefile.
: "${LIBTOOL:=libtool}"
: "${CC:=cc}"

if [ "$#" -ne "1" ]; then
	echo "Usage: $0 object_file"
	exit 1
fi

case $KERNEL_NAME in
	MINGW32_NT*)
		BASENAME=`echo $1 | sed -e 's/_dat\.o$//'`
		;;
	*)
		BASENAME=`echo $1 | sed -e 's/_dat\.la$//' -e 's/_dat\.a$//'`
		BASENAME=`echo $BASENAME | sed -e 's/^lib//'`
		;;
esac

# Wrap pkgdata-generated object files as a libtool convenience library
# (lib${BASENAME}_dat.la) so libtool can link them into shared libraries
# without emitting "linking shared library against static library" warnings.
# The objects produced by pkgdata contain only ICU resource data (no
# relocations), so they are position-independent regardless of -fPIC and
# safe to label as pic_object.
wrap_as_la() {
	mkdir -p .libs ../../.libs
	LTVERS=`${LIBTOOL} --version |
	    sed -e 's/^\([^ ]*\) (GNU \(.*\)) \(.*\)$/\1 - GNU \2 \3/' -e q`
	LTFILES=""
	for OBJFILE in *.o ; do
		LTFILE=${OBJFILE%.o}.lo
		mv "${OBJFILE}" .libs/
		{
			echo "# ${OBJFILE} - a libtool object file"
			echo "# Generated by ${LTVERS}"
			echo "pic_object='.libs/${OBJFILE}'"
			echo "non_pic_object=none"
		} > "${LTFILE}"
		LTFILES="${LTFILES} ${LTFILE}"
	done
	${LIBTOOL} --mode=link --tag=CC ${CC} -o ../../lib${BASENAME}_dat.la ${LTFILES}
}

# Determine if this is a sub-component of libaltfs or internal_error.
# Sub-components use files like ${BASENAME}_root.txt inside a parent directory.
SUBCOMP_DIR=""
case $BASENAME in
	lc|lg|li|lb|lp|lf|lj|lx)
		SUBCOMP_DIR="libaltfs"
		;;
	ei|ed)
		SUBCOMP_DIR="internal_error"
		;;
esac

if [ -n "$SUBCOMP_DIR" ]; then
	# Sub-component mode: copy ${BASENAME}_*.txt from SUBCOMP_DIR into work_${BASENAME}
	cd ${SUBCOMP_DIR}

	make_obj() {
		echo "Processing sub-component ${BASENAME} from ${SUBCOMP_DIR}"

		WORKDIR="work_${BASENAME}"
		# Create a fresh work directory
		if [ -d "${WORKDIR}" ]; then
			rm -rf "${WORKDIR}"
		fi
		mkdir "${WORKDIR}"

		# Copy sub-component txt files, renaming ${BASENAME}_foo.txt -> foo.txt
		for src_file in ${BASENAME}_*.txt; do
			dst_file=`echo "$src_file" | sed -e "s/^${BASENAME}_//"`
			cp "$src_file" "${WORKDIR}/${dst_file}"
		done

		# Generate files
		${GENRB} -d "${WORKDIR}" -q "${WORKDIR}"/*.txt
		cd "${WORKDIR}"
		ls *.res >packagelist.txt
		${PKGDATA} -p ${BASENAME} -m static -q packagelist.txt >/dev/null

		case $KERNEL_NAME in
			MINGW32_NT*)
				mv ${BASENAME}.dat ../../
				;;
			FreeBSD|NetBSD)
				# pkgdata produced lib${BASENAME}.a — explode it so the
				# constituent object files can be wrapped uniformly.
				ar x lib${BASENAME}.a
				rm lib${BASENAME}.a
				wrap_as_la
				;;
			*)
				wrap_as_la
				;;
		esac

		# Clean up
		cd ..
		rm -rf "${WORKDIR}"
	}

	# Check whether we need to do anything
	if [ -f "../$1" ]; then
		for file in ${BASENAME}_*.txt; do
			if [ "$file" -nt "../$1" ]; then
				make_obj
				exit 0
			fi
		done
	else
		make_obj
	fi
else
	# Original mode: directory-based bundles (e.g. bin_altfs, tape_common)
	cd ${BASENAME}

	make_obj() {
		echo "Processing ${BASENAME}"

		# Create a fresh work directory
		if [ -d work ]; then
			rm -rf work
		fi
		mkdir work

		# Generate files
		${GENRB} -d work -q *.txt
		cd work
		ls *.res >packagelist.txt
		${PKGDATA} -p ${BASENAME} -m static -q packagelist.txt >/dev/null

		case $KERNEL_NAME in
			MINGW32_NT*)
				mv ${BASENAME}.dat ../../
				;;
			FreeBSD|NetBSD)
				ar x lib${BASENAME}.a
				rm lib${BASENAME}.a
				wrap_as_la
				;;
			*)
				wrap_as_la
				;;
		esac

		# Clean up
		cd ..
		rm -rf work
	}

	# Check whether we need to do anything
	if [ -f "../$1" ]; then
		for file in *.txt; do
			if [ "$file" -nt "../$1" ]; then
				make_obj
				exit 0
			fi
		done
	else
		make_obj
	fi
fi
